### ISSUE TITLE
enableTimeCoverage needs enable=true

### ISSUE THREAD

**Issue by hblitza** [meggsimum/geoserver-node-client#103]
# Question
Having tested the `layers.enablingTimeCoverage` function, I stumpled upon the possibly missing parameter `enabled=true`.  
I had to add it to the `dimensionInfo` object in order to actually enable the time dimension.
https://github.com/meggsimum/geoserver-node-client/blob/659d31fc5536c0a5d33b4f8edd1bdf0f569f65a4/src/layer.js#L485

Can somebody reproduce this?

**Comment by chrismayer** [comment]
As far as I remember setting `enable=true` was not necessary. Currently I do not have dataset to test this. On the other side setting it explicitly should not hurt, I guess. Since the function is named **enable**TimeCoverage the `enable=true` could be set in the function itself and does not need to be a parameter. What do you think @hblitza ? Are you willing to come up with a PR?

**Comment by hblitza** [comment]
Allright I see, thanks for the fast reply and for checking!

**Comment by chrismayer** [comment]
Thanks for getting in action so quick and providing the @hblitza!
